version: '3.8'

services:
  # سرویس اپلیکیشن برای محیط توسعه
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: parnamyadak_app_dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://parnamyadak_user:parnamyadak_pass@db:5432/parnamyadak_db
      - SECRET_KEY=dev-secret-key
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      - db
      - redis
    networks:
      - parnamyadak_network
    command: ["python", "run.py"]

  # سرویس دیتابیس PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: parnamyadak_db_dev
    restart: unless-stopped
    environment:
      - POSTGRES_DB=parnamyadak_db
      - POSTGRES_USER=parnamyadak_user
      - POSTGRES_PASSWORD=parnamyadak_pass
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - parnamyadak_network

  # سرویس Redis برای کش
  redis:
    image: redis:7-alpine
    container_name: parnamyadak_redis_dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - parnamyadak_network

volumes:
  postgres_data_dev:
    driver: local
  redis_data_dev:
    driver: local

networks:
  parnamyadak_network:
    driver: bridge