services:
  # ========================================
  # NGINX Reverse Proxy
  # ========================================
  nginx:
    image: nginx:latest
    container_name: parnamyadak_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # اتصال فایل کانفیگ Nginx که در مرحله بعد می‌سازیم
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # اتصال پوشه گواهی‌های SSL به صورت فقط خواندنی
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
      - bot
    networks:
      - parnamyadak_network

  # ========================================
  # سرویس اپلیکیشن اصلی (پنل)
  # ========================================
  app:
    # فرض بر این است که Dockerfile پنل در همین پوشه ('.') قرار دارد
    build: .
    container_name: parnamyadak_app
    restart: unless-stopped
    env_file:
      # فایل متغیرهای محیطی پنل
      - .env
    command:
      # Gunicorn با worker sync (بدون نیاز به gevent)
      [
        "gunicorn",
        "--worker-class", "sync",
        "-w", "4",
        "-b", "0.0.0.0:5000",
        "--timeout", "120",
        "--keep-alive", "2",
        "gunicorn_entrypoint:app"
      ]
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./static/receipts:/app/static/receipts
      - ./static/product_pics:/app/static/product_pics
      - ./static/mechanic_licenses:/app/static/mechanic_licenses
      - ./static/bot_receipts:/app/static/bot_receipts
    depends_on:
      - db
      - redis
    networks:
      - parnamyadak_network

  # ========================================
  # سرویس ربات تلگرام
  # ========================================
  bot:
    # مسیر پوشه ربات شما
    build: ./ParnamYadak_bot
    container_name: parnamyadak-bot
    restart: unless-stopped
    env_file:
      # فایل متغیرهای محیطی ربات
      - ./ParnamYadak_bot/bot_config.env
    networks:
      - parnamyadak_network

  # ========================================
  # سرویس دیتابیس PostgreSQL
  # ========================================
  db:
    image: postgres:15-alpine
    container_name: parnamyadak_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - "5432:5432"
    networks:
      - parnamyadak_network

  # ========================================
  # سرویس Redis برای کش
  # ========================================
  redis:
    image: redis:7-alpine
    container_name: parnamyadak_redis
    hostname: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - parnamyadak_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  parnamyadak_network:
    driver: bridge
